MyBlog/blueprints/admin.py
# -*- coding: utf-8 -*-
import os

from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint, send_from_directory
from flask_login import login_required, current_user, fresh_login_required
from flask_ckeditor import upload_success, upload_fail

from MyBlog.extensions import db
from MyBlog.forms import SettingForm, PostForm, ChangePasswordForm, DeleteAccountForm
from MyBlog.models import Post, Category, Comment
from MyBlog.utils import redirect_back, allowed_file
from MyBlog.utils import confirm_required
admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        db.session.commit()
        flash('设置已更新.', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
@login_required
@confirm_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(Post.author == current_user).order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['MYBLOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('博文已创建.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('博文已更新.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id
    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('博文已删除.', 'success')
    return redirect_back()


@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
@confirm_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('已关闭评论.', 'success')
    else:
        post.can_comment = True
        flash('已打开评论.', 'success')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/comment/manage')
@login_required
@confirm_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all')
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MYBLOG_COMMENT_PER_PAGE']
    if filter_rule == 'unread':
        user_id = current_user.id
        filtered_comments = Comment.query.join(Post, Post.id == Comment.post_id_r).filter(Post.author_id == user_id)
        filtered_comments = filtered_comments.filter(Comment.reviewed== False)
    else:
        user_id=current_user.id
        filtered_comments = Comment.query.join(Post, Post.id == Comment.post_id).filter(Post.author_id == user_id)
    pagination = filtered_comments.order_by(Comment.timestamp.desc()).paginate(page, per_page=per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
@confirm_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    post = Post.query.filter_by(id=comment.post_id_r).first()
    comment.reviewed = True
    comment.post = post
    db.session.commit()
    flash('评论已通过.', 'success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除.', 'success')
    return redirect_back()


@admin_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['MYBLOG_UPLOAD_PATH'], filename)


@admin_bp.route('/upload', methods=['POST'])
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('仅图片!')
    f.save(os.path.join(current_app.config['MYBLOG_UPLOAD_PATH'], f.filename))
    url = url_for('.get_image', filename=f.filename)
    return upload_success(url, f.filename)


@admin_bp.route('/settings/account/delete', methods=['GET', 'POST'])
@fresh_login_required
def delete_account():
    form = DeleteAccountForm()
    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        flash('账号已删除', 'success')
        return redirect(url_for('blog.index'))
    return render_template('admin/delete_account.html', form=form)


@admin_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()
            flash('新密码已设置.', 'success')
            return redirect(url_for('blog.index'))
        else:
            flash('旧密码不正确.', 'warning')
    return render_template('admin/change_password.html', form=form)

MyBlog/blueprints/blog.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request, current_app, Blueprint
from flask_login import current_user, login_required
from flask import Markup
from MyBlog.extensions import db
from MyBlog.forms import AdminCommentForm
from MyBlog.models import Post, Category, Comment
from MyBlog.utils import confirm_required

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        per_page = current_app.config['MYBLOG_POST_PER_PAGE']
        pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
        posts = pagination.items
        return render_template('blog/index.html', pagination=pagination, posts=posts)
    else:
        return redirect(url_for('auth.login'))


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MYBLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['MYBLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        reviewed = False
        if current_user == post.author:
            reviewed = True

    if form.validate_on_submit():
        if current_user.confirmed:
            author = current_user._get_current_object()
            author_name = author.username
            body = form.body.data
            if post.author == current_user:
                comment = Comment(
                    author=author, author_name=author_name, body=body,
                    post=post, reviewed=reviewed)
            else:
                comment = Comment(
                    author=author, author_name=author_name, body=body,
                    post_id_r=post.id, reviewed=reviewed)

            replied_id = request.args.get('reply')
            if replied_id:
                replied_comment = Comment.query.get_or_404(replied_id)
                comment.replied = replied_comment
            db.session.add(comment)
            db.session.commit()
            if post.author == current_user:
                flash('评论发布成功.', 'success')
            else:
                flash('你的评论将在作者审阅后发布.', 'info')
            return redirect(url_for('.show_post', post_id=post_id))
        else:
            message = Markup(
                '请先在邮箱中确认您的账号.'
                '没收到邮件?'
                '<a class="alert-link" href="%s">重新发送确认邮件</a>' %
                url_for('auth.resend_confirm_email'))
            flash(message, 'warning')
            return redirect(url_for('.show_post', post_id=post_id))

    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)


@blog_bp.route('/reply/comment/<int:comment_id>')
@login_required
@confirm_required
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('评论已关闭.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author_name) + '#comment-form')

MyBlog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', post_id=post.id) }}">阅读更多</a></small>
        </p>
        <small>
            评论数: <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            类别: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>暂无博文.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">现在发布博文</a>
        {% endif %}
    </div>
{% endif %}

MyBlog/templates/blog/_sidebar.html
{% if categories %}
    <div class="card mb-3">
        <div class="card-header">类别</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

MyBlog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>类别: {{ category.name }}</h1>
        <p class="text-muted">共 {{ category.posts|length }} 篇博文</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

MyBlog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}

    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endif %}
{% endblock %}

MyBlog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}

        </h1>
        <small>
            作者: {{ post.author.name }}<br>
            类别: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a><br>
            发布日期: {{ moment(post.timestamp).format('LL') }}
        </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>

            <div class="comments" id="comments">
                <h3>{{ pagination.total }} 评论
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
                            最新</a>
                    </small>
                    {% if current_user.is_authenticated and post.author == current_user%}
                        <form class="float-right" method="post"
                              action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <button type="submit" class="btn btn-warning btn-sm">
                                {% if post.can_comment %}关闭{% else %}打开{% endif %} 评论
                            </button>
                        </form>
                    {% endif %}
                </h3>
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="#"  target="_blank">
                                            {{ comment.author_name }}
                                        </a>
                                        {% if comment.author == post.author %}
                                            <span class="badge badge-primary">作者</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">回复</span>{% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                        {{ moment(comment.timestamp).fromNow() }}
                                    </small>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-dark reply-body">{{ comment.replied.author_name }}:
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {%- endif -%}
                                <p class="mb-1">{{ comment.body }}</p>
                                <div class="float-right">
                                    <a class="btn btn-light btn-sm"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">回复</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5>暂无评论.</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if request.args.get('reply') %}
                <div class="alert alert-dark">
                    Reply to <strong>{{ request.args.get('author') }}</strong>:
                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">取消</a>
                </div>
            {% endif %}
            {% if post.can_comment %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip"><h5>评论已关闭.</h5></div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}